import { StyleSheet } from "react-native";
import Colors from "./Colors";

export const styles = StyleSheet.create({
    screen: {
        backgroundColor: Colors.blueDark,
        minHeight: '100%',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    button: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 15,
        paddingBottom: 15,
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 12,
        backgroundColor: Colors.blue,
    },
    roundButton: {
        width: 150,
        height: 150,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderColor: Colors.blueLight,
        borderStyle: 'solid',
        borderWidth: 6,
        backgroundColor: Colors.blue,
        shadowColor: Colors.white,
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    roundActiveButton: {
        width: 150,
        height: 150,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderColor: Colors.green,
        borderStyle: 'solid',
        borderWidth: 6,
        backgroundColor: Colors.green,
        shadowColor: Colors.white,
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    banner: {
        justifyContent: 'center',
        alignItems: 'center',
        margin: 40,
        padding: 10,
        borderRadius: 12,
        backgroundColor: Colors.blue,
    },
    server: {
        marginTop: 5,
        marginBottom: 5,
        marginLeft: 10,
        marginRight: 10,
        paddingTop: 15,
        paddingBottom: 15,
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 12,
        backgroundColor: Colors.blue,
    },
});
